url: https://oheven.github.io/chang_blog/             # Site url, without a slash at the end.
auto: true
server: true

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
exclude: ['README.md', 'src/', 'node_modules', 'package.json', 'Gruntfile.js', '*.command']
permalink: /:year/:month/:title
paginate: 10
paginate_path: "/page:num"
